### ISSUE TITLE
I can't change my projekts

### ISSUE THREAD

**Issue by RoopeSaukkonen** [sprintly/sprintly-ui#6]
I can't change my projects in sprintly because I can't hover over "projects" drop down menu. 

See the picture bellow to see the button.

![image](https://cloud.githubusercontent.com/assets/4973627/6268975/19edb618-b859-11e4-9718-6117cfc5a8cd.png)

**Comment by florapdx** [comment]
Hi Roope, 
It looks like you're having an issue with https://sprint.ly, not specifically the code in this repository (which isn't yet being used in our online app).  To log issues with the product, please use the "Support" menu at the bottom of any page when logged into your sprint.ly account and our support specialist can help you.

**Comment by RoopeSaukkonen** [comment]
Ok thanks.
